import { login, signup } from '../languages/auth';
export const en = {
  loginScreen: {
    title: login.title.en,
    nameLabel: login.nameLabel.en,
    namePlaceholder: login.namePlaceholder.en,
    passwordLabel: login.passwordLabel.en,
    passwordPlaceholder: login.passwordPlaceholder.en,
    showPassword: login.showPassword.en,
    forgotPassword: login.forgotPassword.en,
    loginBtn: login.loginBtn.en,
    loadingLoginBtn: login.loadingLoginBtn.en,
    loginTextLink: login.loginTextLink.en,
    loginLink: login.loginLink.en,
    loginError: login.loginError.en,
    missingFields: login.missingFields.en,
  },
  signupScreen: {
    title: signup.title.en,
    emailLabel: signup.emailLabel.en,
    emailPlaceholder: signup.emailPlaceholder.en,
    passwordLabel: signup.passwordLabel.en,
    passwordPlaceholder: signup.passwordPlaceholder.en,
    confirmPasswordLabel: signup.confirmPasswordLabel.en,
    confirmPasswordPlaceholder: signup.confirmPasswordPlaceholder.en,
    showPassword: signup.showPassword.en,
    signupBtn: signup.signupBtn.en,
    loadingSignupBtn: signup.loadingSignupBtn.en,
    signupTextLink: signup.signupTextLink.en,
    signupLink: signup.signupLink.en,
    wrongPasswords: signup.wrongPasswords.en,
    shortPassword: signup.shortPassword.en,
    userExists: signup.userExists.en,
  },
};
export const he = {
  loginScreen: {
    title: login.title.he,
    nameLabel: login.nameLabel.he,
    namePlaceholder: login.namePlaceholder.he,
    passwordLabel: login.passwordLabel.he,
    passwordPlaceholder: login.passwordPlaceholder.he,
    showPassword: login.showPassword.he,
    forgotPassword: login.forgotPassword.he,
    loginBtn: login.loginBtn.he,
    loadingLoginBtn: login.loadingLoginBtn.he,
    loginTextLink: login.loginTextLink.he,
    loginLink: login.loginLink.he,
    loginError: login.loginError.he,
    missingFields: login.missingFields.he,
  },
  signupScreen: {
    title: signup.title.he,
    emailLabel: signup.emailLabel.he,
    emailPlaceholder: signup.emailPlaceholder.he,
    passwordLabel: signup.passwordLabel.he,
    passwordPlaceholder: signup.passwordPlaceholder.he,
    confirmPasswordLabel: signup.confirmPasswordLabel.he,
    confirmPasswordPlaceholder: signup.confirmPasswordPlaceholder.he,
    showPassword: signup.showPassword.he,
    signupBtn: signup.signupBtn.he,
    loadingSignupBtn: signup.loadingSignupBtn.he,
    signupTextLink: signup.signupTextLink.he,
    signupLink: signup.signupLink.he,
    missingFields: signup.missingFields.he,
    wrongPasswords: signup.wrongPasswords.he,
    shortPassword: signup.shortPassword.he,
    userExists: signup.userExists.he,
  },
};
